name: documentation

on:
  push:
    branches:
#      - "develop/**"    # For development and testing
      - "master"
    paths:
#     Documentation
#     Doc - CI workflow
      - ".github/workflows/documentation.yaml"
      - "scripts/ci/**documentation**.sh"
#     Doc - Font-End config
      - "docs/package.json"
      - "docs/pnpm-lock.yaml"
#     Doc - Docusaurus config
      - "docs/docusaurus.config.ts"
#     Doc - Content
      - "docs/**/*.md"
      - "docs/**/*.mdx"
      - "docs/**/*.ts"
      - "docs/**/*.tsx"
      - "docs/**/*.js"
      - "docs/**/*.jsx"
      - "docs/**/*.css"

permissions:
  contents: write
  id-token: write
  pages: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy_documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup pnpm first
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      # Then setup Node.js with pnpm cache
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
          cache-dependency-path: docs/pnpm-lock.yaml

      - name: Install dependencies
        working-directory: docs
        run: pnpm install --no-frozen-lockfile

      - name: Build website
        working-directory: docs
        run: pnpm build

      # Setup Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Upload artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./docs/build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
